// <auto-generated />

// Namespace and using directives.
using CarStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

// Namespace for migrations and snapshot.
namespace CarStore.Migrations
{
    // DbContext attribute specifying the associated DbContext type.
    [DbContext(typeof(CarStoreDbContext))]
    // Partial class for the model snapshot, inheriting from ModelSnapshot.
    partial class CarStoreDbContextModelSnapshot : ModelSnapshot
    {
        // Override of the BuildModel method to define the model for the snapshot.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // Disable specific warnings related to EF Core versions.
#pragma warning disable 612, 618
            // Annotations for the model.
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Use SQL Server identity columns.
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Define the entity for the 'Car' model.
            modelBuilder.Entity("CarStore.Models.Car", b =>
            {
                // Define properties for the 'Car' entity.
                b.Property<long>("CarID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                // Use SQL Server identity column for 'CarID'.
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CarID"));

                // Other properties for the 'Car' entity.
                b.Property<string>("Condition")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Make")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Model")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                // Define the primary key for the 'Car' entity.
                b.HasKey("CarID");

                // Define the table name for the 'Car' entity.
                b.ToTable("Cars");
            });
#pragma warning restore 612, 618
        }
    }
}
